[package]
name = "aoc_2022"
version = "0.1.0"
authors = ["Tunahan Karlibas <me@dvtkrlbs.me>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
atoi_radix10 = "0.0.1"
btoi = "0.4.2"
itertools = "0.10.5"
rayon = "1.6.0"

[profile.release]
debug = true
